sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -U pytest-cov
install:
  - pip install -r requirements.txt
  - pip install ".[test]"  .
script:
  - pytest --cov-report term --cov=src tests/
after_success:
  - codecov